import Head from "next/head";
import styles from "@/styles/Home.module.css";
import BuildCard from "./components/BuildCard";
import GetStarted from "./components/GetStarted";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header
        className={`pt-20 px-6 flex flex-col items-center xl:flex-row xl:pt-[129px] xl:pb-[250px] xl:items-end ${styles.header}`}
      >
        <h1 className={`mb-5 md:mb-6 xl:mb-0 xl:mr-[30px] ${styles.heading}`}>
          Find the <br /> best{" "}
          <span className={`${styles.headingSpan}`}>talent</span>
        </h1>

        <p
          className={` mb-48 md:mb-64 xl:mb-0 xl:ml-auto ${styles.headingText}`}
        >
          <span className={styles.bar}></span>
          Finding the right people and building high performing teams can be
          hard. Most companies aren’t tapping into the abundance of global
          talent. We’re about to change that.
        </p>
      </header>
      <main className={` ${styles.main}`}>
        <section className={`pt-16 px-[6%] w-[100%] ${styles.build}`}>
          <div className={`xl:flex xl:w-[100%] xl:py-[80px] ${styles.buildContainer}`}>
            <div className={` ${styles.mainBar}`}></div>
            <h2 className={`mb-14 w-60 md:w-[100%] xl:w-[445px] xl:ml-[-50px] xl:mr-32 mt-8 xl:mt-14 ${styles.heading2}`}>
              Build & manage distributed teams like no one else.
            </h2>
            <div className={`xl:mt-14`}>
            <BuildCard
              src="./images/icon-person.svg"
              heading="Experienced Individuals"
              text="Our network is made up of highly experienced professionals who are passionate about what they do."
            />

            <BuildCard
              src="./images/icon-cog.svg"
              heading="Easy to Implement"
              text="Our processes have been refined over years of implementation meaning our teams always deliver."
            />

            <BuildCard
              src="./images/icon-chart.svg"
              heading="Enhanced Productivity"
              text="Our customized platform with in-built analytics helps you manage your distributed teams."
            />
            </div>
            
          </div>
        </section>

        <GetStarted />
      </main>
    </>
  );
}
